# code: language=ansible
---

- name: restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted