{
 "title": "Beernary Public Dashboard",
 "time": { "from": "now-48h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Beernary consumption - Current (last 1h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Approx. current consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT sum(\"pulses\")  / 1000 FROM \"autogen\".\"draft\" WHERE (\"tap\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT sum(\"pulses\")  / 1000 FROM \"autogen\".\"draft\" WHERE (\"tap\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Current consumption distribution by user - Tap 1",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" }
     ],
     "measurement": "draft",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Active drinkers count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '1') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '2') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Beernary consumption - Current (last 24h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Approx. current consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT sum(\"pulses\")  / 1000 FROM \"autogen\".\"draft\" WHERE (\"tap\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT sum(\"pulses\")  / 1000 FROM \"autogen\".\"draft\" WHERE (\"tap\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Current consumption distribution by user - Tap 1",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" }
     ],
     "measurement": "draft",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Active drinkers count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '1') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '2') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Beernary consumption - Total (selected timeframe)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Approx. total consumption - Tap 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Total consumption distribution by user - Tap 1",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" }
     ],
     "measurement": "draft",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Total drinkers count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '1') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '2') AND $timeFilter\n)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Approx. Total consumption per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "draft",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "draft",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Active drinkers count per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "alias": "Tap 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '1') AND $timeFilter\n)\nGROUP BY time(1h)\nfill(null)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Tap 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "user::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "draft",
     "query": "SELECT COUNT(DISTINCT \"user\") as \"UserCount\"\nFROM (\n\tSELECT \"time\",\"pulses\",\"user\"::tag\n\tFROM \"autogen\".\"draft\"\n\tWHERE (\"tap\"::tag = '2') AND $timeFilter\n)\nGROUP BY time(1h)\nfill(null)",
     "select": [
      [
       { "params": [ "pulses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tap::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  }
 ]
}