# code: language=ansible
---

- name: "Disable IPV6 stack via sysctl"
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: "true"
    state: "present"
    reload: "true"
  with_items:
    - "net.ipv6.conf.all.disable_ipv6"
    - "net.ipv6.conf.default.disable_ipv6"

# Usually: not done because of operational stability
# Here: "enforce" to keep compability with updates
- name: "Update Raspberry OS to latest APT packages"
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    autoremove: true
    autoclean: true
  become: true
  when: os_configuration_apt_upgrade

- name: "Allow Beernary team's SSH keys for root user"
  ansible.posix.authorized_key:
    user: "root"
    key: "{{ item }}"
    state: "present"
  loop: "{{ os_configuration_ssh_keys }}"

- name: "Disable unrequired Raspberry OS services"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: "stopped"
  loop: "{{ os_configuration_unrequired_services }}"

- name: "Deploy hardened OpenSSH configuration"
  ansible.builtin.template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: "root"
    group: "root"
    mode: "0744"
    backup: true
  notify: "Restart sshd"

- name: "Deploy MOTD with status informations"
  ansible.builtin.template:
    src: "motd.j2"
    dest: "/etc/motd"
    owner: "root"
    group: "root"
    mode: "0744"
    backup: true
  changed_when: false
